proxys: 
  - 
    name: test1 # 代理组名
    listen: 0.0.0.0:9898 # 代理组监听地址和端口
    reverse: # 被代理地址列表，可多个
      - 127.0.0.1:8114
      - 127.0.0.1:8115
  - 
    name: test2
    listen: 0.0.0.0:8989
    reverse: 
      - 127.0.0.1:8114
      - 127.0.0.1:8115
  - 
    name: mysql
    listen: 0.0.0.0:3308
    reverse: 
      - 127.0.0.1:3306
